package com.amazonaws.mobile.api;

//
//  CloudLogicAPIFactory.java
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.16
//

/**
 * Produces instances of Cloud Logic API configuration.
 */
public class CloudLogicAPIFactory {

    private CloudLogicAPIFactory() {}

    /**
     * Gets the configured micro-service instances.
     * @return
     */
    public static CloudLogicAPIConfiguration[] getAPIs() {
        final CloudLogicAPIConfiguration[] apis = new CloudLogicAPIConfiguration[] {
                new CloudLogicAPIConfiguration("I-Rail",
                                              "I-Rail APIs for Law Enforcement",
                                              "https://h9ydfojrbi.execute-api.us-east-1.amazonaws.com/prod",
                                              new String[] {
                                                  "/tracker",
                                                  "/spot"
                                              },
                                              com.amazonaws.mobile.api.idh9ydfojrbi.IRailClient.class),
        };

        return apis;
    }
}
